@node Invoking
@chapter Invoking

@command{learn-your-telephone-number} takes exactly one
argument: your telephone number. It will ask you to enter
it --- so you should not invoke @command{learn-your-telephone-number}
directly.

If the telephone number you enters matches the specified
number, the program will exit with status 0. If they do
not match, the program will show the difference and exit
with status 1.

On failure the program exits with status 2.

