@node Overview
@chapter Overview

@command{learn-your-telephone-number} is a simple command
that can be used to force yourself learn your telephone
number, or any sequence of digits.

@command{learn-your-telephone-number} recognises @code{+}
as an alias for @code{00}. All other non-digits are ignored.

It is recommended to make your shell sometimes when opened,
starts this program. Or when you log in on your laptop.

